version: "3.3"

services:
  php-fpm:
    build:
      context: '.'
      dockerfile: './docker/Dockerfile'
    container_name: 'contacts-php'
    volumes:
      - ./:/var/www/localhost/htdocs
    ports:
      - '8080:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - 'contacts'
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: app
    volumes:
      - ./.docker-volumes/mysql/:/var/lib/mysql
    networks:
      - contacts

networks:
  contacts:
    name: 'contacts'